version: 0.2

phases:
  install:
    commands:
      - echo "Login to Docker registry or ECR if needed"
  pre_build:
    commands:
      - echo "Pre-build commands, if any"
  build:
    commands:
      - docker-compose build
      - docker tag web:latest mab3321/web:latest
  post_build:
    commands:
      - echo "Push Docker image to registry or ECR if needed"
      - docker push mab3321/web:latest
